export const PERMISSIONS = {
  VIEW_DASHBOARD: "VIEW_DASHBOARD",
  VIEW_ABOUT: "VIEW_ABOUT",
  VIEW_SETTINGS: "VIEW_SETTINGS",
  VIEW_REPORTS: "VIEW_REPORTS",
  VIEW_GEOGRAPHY: "VIEW_GEOGRAPHY",
  VIEW_CONVERSATIONS: "VIEW_CONVERSATIONS",
  VIEW_DEALS: "VIEW_DEALS",
  VIEW_EXPORT: "VIEW_EXPORT",
};
