export const RouteConstants = {
  ROUTE_DASHBOARD: "/dashboard",
  ROUTE_LOGIN: "/login",
  ROUTE_ABOUT: "/about",
  ROUTE_SETTINGS: "/settings",
  ROUTE_REPORTS: "/reports",
  ROUTE_GEOGRAPHY: "/geography",
  ROUTE_CONVERSATION: "/conversation",
  ROUTE_DEALS: "/deals",
  ROUTE_EXPORT: "/export",
  ROUTE_SIGNUP: "/signup",
  ROUTE_VERIFY: "/verify",
  ROUTE_FORGOT_PASSWORD: "/forgot-password",
  ROUTE_RESET_PASSWORD: "/reset-password",
};
