const marbles = [
  {
    name: "Carrara Marble",
    city: "Carrara",
    state: "Tuscany",
    country: "Italy",
    price_per_sqft: 400,
  },
  {
    name: "Calacatta Gold Marble",
    city: "Carrara",
    state: "Tuscany",
    country: "Italy",
    price_per_sqft: 800,
  },
  {
    name: "Statuario Marble",
    city: "Carrara",
    state: "Tuscany",
    country: "Italy",
    price_per_sqft: 700,
  },
  {
    name: "Botticino Marble",
    city: "Botticino",
    state: "Lombardy",
    country: "Italy",
    price_per_sqft: 300,
  },
  {
    name: "Rosso Levanto Marble",
    city: "Levanto",
    state: "Liguria",
    country: "Italy",
    price_per_sqft: 500,
  },
  {
    name: "Makrana White Marble",
    city: "Makrana",
    state: "Rajasthan",
    country: "India",
    price_per_sqft: 250,
  },
  {
    name: "Ambaji White Marble",
    city: "Ambaji",
    state: "Gujarat",
    country: "India",
    price_per_sqft: 200,
  },
  {
    name: "Rajnagar White Marble",
    city: "Rajnagar",
    state: "Rajasthan",
    country: "India",
    price_per_sqft: 150,
  },
  {
    name: "Onyx Green Marble",
    city: "Udaipur",
    state: "Rajasthan",
    country: "India",
    price_per_sqft: 300,
  },
  {
    name: "Rainforest Brown Marble",
    city: "Bidasar",
    state: "Rajasthan",
    country: "India",
    price_per_sqft: 200,
  },
];
